version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      DEBUG: "TRUE"


    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
      DEBUG: "TRUE"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

      
volumes:
  local_pgdata:
  pgadmin-data: