version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin


    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  python:
    image: test
    container_name: python
    restart: always
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin

volumes:
  local_pgdata:
  pgadmin-data: